export const fruits = [
  "Apple",
  "Apricots",
  "Avocados",
  "Bananas",
  "Boysenberries",
  "Blueberries",
  "Cherry",
  "Cantaloupe",
  "Cucumbers",
  "Dates",
  "Dragon Fruit",
  "Elderberry",
  "Eggfruit",
  "Fig",
  "Farkleberry",
  "Finger Lime",
  "Grapefruit",
  "Grapes",
  "Gooseberries",
  "Guava",
  "Honeydew Melon",
  "Hackleberry",
  "Indian Prune",
  "Indonesian Lime",
  "Indian Fig",
  "Jackfruit",
  "Jambolan",
  "Java Apple",
  "Kiwi",
  "Kaffir Lime",
  "Kumquat",
  "Lime (Lemon)",
  "Longan",
  "Lychee",
  "Loquat",
  "Mango",
  "Mandarin Orange",
  "Mulberry",
  "Melon",
  "Nectarine",
  "Navel Orange",
  "Nashi Pear (Asian Pear)",
  "Olive",
  "Oranges",
  "Ogeechee Limes",
  "Oval Kumquat",
  "Papaya",
  "Persimmon",
  "Paw Paw",
  "Prickly Pear",
  "Peach",
  "Pomegranate",
  "Pineapple",
  "Quince",
  "Queen Anne Cherry",
  "Quararibea cordata (Chupa Chupa)",
  "Rambutan",
  "Raspberries",
  "Rose Hips",
  "Star Fruit",
  "Strawberries",
  "Sugar Baby Watermelon",
  "Tomato",
  "Tangerine",
  "Tamarind",
  "Tart Cherries",
  "Ugli Fruit",
  "Uniq Fruit",
  "Ugni",
  "Vanilla Bean",
  "Velvet Pink Banana",
  "Voavanga",
  "Watermelon",
  "Wolfberry",
  "White Mulberry",
  "Xigua (Chinese Watermelon)",
  "Ximenia caffra fruit",
  "Xango Mangosteen Fruit Juice",
  "Yellow Passion Fruit",
  "Yunnan Hackberry",
  "Yangmei",
  "Zig Zag Vine fruit",
  "Zinfandel Grapes",
  "Zucchini (a fruit, like tomatoes)",
];
